/**
 *
 * IssuesPage
 *
 */

import React, { useEffect } from 'react';

import { Layout, Menu, Breadcrumb, Icon } from 'antd';

const { Footer, Sider } = Layout;
const { SubMenu } = Menu;
import { Helmet } from 'react-helmet';
import { FormattedMessage } from 'react-intl';
import { useSelector, useDispatch } from 'react-redux';
import { createStructuredSelector } from 'reselect';

import { useInjectSaga } from 'utils/injectSaga';
import { useInjectReducer } from 'utils/injectReducer';
import {
  makeSelectIssues,
  makeSelectIsLoading,
  makeSelectError,
} from './selectors';
import reducer from './reducer';
import saga from './saga';
import messages from './messages';
import Sidebar from 'components/App/Sidebar';
import Header from 'components/App/Header';

import background from 'images/background.svg';
import { getIssuesAction } from './actions';

const stateSelector = createStructuredSelector({
  issues: makeSelectIssues(),
  isLoading: makeSelectIsLoading(),
  error: makeSelectError(),
});

function IssuesPage() {
  useInjectReducer({ key: 'issuesPage', reducer });
  useInjectSaga({ key: 'issuesPage', saga });

  /* eslint-disable no-unused-vars */
  const { issues, isLoading, error } = useSelector(stateSelector);
  const dispatch = useDispatch();
  const handleIssues = () => dispatch(getIssuesAction());
  /* eslint-enable no-unused-vars */

  useEffect(() => {
    handleIssues();
  }, []);

  return (
    <>
      <Helmet>
        <title>IssuesPage - codefen.com</title>
        <meta name="description" content="Description of IssuesPage" />
      </Helmet>

      <div>
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br /> <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
      </div>
    </>
  );
}

IssuesPage.propTypes = {};

export default IssuesPage;
